{% set name = "pyfume" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5305b93b015fbb4d650cac33ef6881d9e81b3a8c5bfadf149c41485236667df5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy
    - numpy
    - simpful
    - fst-pso
    - pandas

test:
  imports:
    - pyfume
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CaroFuchs/pyFUME
  summary: A Python package for fuzzy model estimation
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgruening
