{% set name = "pyfume" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyFUME-{{ version }}.tar.gz
  sha256: f09f6a85269395bfca8828de82673c89a19a64e5c9d0f93512ab8e4c4514b56d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy
    - numpy
    - simpful
    - fst-pso
    - pandas

test:
  imports:
    - pyfume
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CaroFuchs/pyFUME
  summary: A Python package for fuzzy model estimation
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgruening
